package com.crs.model;

import java.util.List;

public class AcademicOfficer extends User {
    private static final long serialVersionUID = 6L;
    private String faculty;
    private String employeeId;

    public AcademicOfficer(String userId, String username, String password, 
                          String email, String fullName, String employeeId, String faculty) {
        super(userId, username, password, email, fullName, Role.ACADEMIC_OFFICER);
        this.employeeId = employeeId;
        this.faculty = faculty;
    }

    @Override
    public String getUserDetails() {
        return String.format("Academic Officer - Employee ID: %s, Faculty: %s, Email: %s",
                employeeId, faculty, getEmail());
    }

    public void checkStudentEligibility(List<Student> students) {
        System.out.println("=== ELIGIBILITY CHECK REPORT ===");
        System.out.println("Generated by: " + getFullName());
        System.out.println("Date: " + java.time.LocalDate.now());
        System.out.println("================================\n");

        int eligibleCount = 0;
        int notEligibleCount = 0;

        for (Student student : students) {
            student.checkEligibility();
            if (student.isEligibleForProgression()) {
                eligibleCount++;
            } else {
                notEligibleCount++;
            }
            System.out.println();
        }

        System.out.println("================================\n");
        System.out.println("SUMMARY:");
        System.out.println("Total Students: " + students.size());
        System.out.println("Eligible for Progression: " + eligibleCount);
        System.out.println("Not Eligible: " + notEligibleCount);
    }

    public void generateBulkAcademicReports(List<Student> students, int semester, int year) {
        System.out.println("=== GENERATING ACADEMIC REPORTS ===");
        System.out.println("Generated by: " + getFullName());
        System.out.println("Semester: " + semester + ", Year: " + year);
        System.out.println("===================================\n");

        for (Student student : students) {
            String report = student.generateAcademicReport(semester, year);
            System.out.println(report);
            System.out.println("===================================\n");
        }
    }

    public String getFaculty() { return faculty; }
    public void setFaculty(String faculty) { this.faculty = faculty; }

    public String getEmployeeId() { return employeeId; }
    public void setEmployeeId(String employeeId) { this.employeeId = employeeId; }
}